development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: agell_development
  pool: 5
  username: Rails.application.credentials.MYSQL.DEV.USER
  password: Rails.application.credentials.MYSQL.DEV.PASSWORD
  host: Rails.application.credentials.MYSQL.HOST

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: agell_test
  pool: 5
  username: Rails.application.credentials.MYSQL.TEST.USER
  password: Rails.application.credentials.MYSQL.TEST.PASSWORD
  host: Rails.application.credentials.MYSQL.HOST


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: agell_production
  pool: 5
  username: Rails.application.credentials.MYSQL.PROD.USER
  password: Rails.application.credentials.MYSQL.PROD.PASSWORD
  host: Rails.application.credentials.MYSQL.HOST

