development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: agell_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: agell_test
  pool: 5
  username: root
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: agell_production
  pool: 5
  username: Rails.application.credentials[:MYSQL][:PROD][:USER]
  password: Rails.application.credentials[:MYSQL][:PROD][:PASSWORD]

